(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(abbrev-file-name "~/.emacs.d/var/abbrev_defs")
 '(ag-highlight-search t)
 '(ag-reuse-buffers t)
 '(bookmark-default-file "~/.emacs.d/var/bookmarks")
 '(browse-url-chromium-program
   "/c/Program Files (x86)/Google/Chrome/Application/chrome.exe")
 '(confirm-kill-emacs nil)
 '(crowi-attachment-save-path "~/.emacs.d/var/crowi/")
 '(crowi-markdown-save nil)
 '(crowi-markdown-save-path "~/.emacs.d/var/crowi/")
 '(cua-enable-cua-keys nil)
 '(cua-mode t nil (cua-base))
 '(custom-enabled-themes (quote (ample-zen)))
 '(custom-safe-themes
   (quote
    ("2a7beed4f24b15f77160118320123d699282cbf196e0089f113245d4b729ba5d" "1db337246ebc9c083be0d728f8d20913a0f46edc0a00277746ba411c149d7fe5" default)))
 '(dashboard-set-file-icons t)
 '(dashboard-set-heading-icons t)
 '(dashboard-set-navigator t)
 '(delete-selection-mode t)
 '(dired-dnd-protocol-alist nil)
 '(dired-dwim-target t)
 '(emojify-emojis-dir "~/.emacs.d/var/emojis")
 '(emojify-program-contexts (quote (comments)))
 '(ensime-sbt-command "cygsbt")
 '(ensime-startup-notification nil)
 '(ensime-startup-snapshot-notification nil)
 '(flycheck-disabled-checkers (quote (python-flake8)))
 '(global-emojify-mode t)
 '(global-flycheck-mode t)
 '(global-hl-line-mode t)
 '(global-undo-tree-mode t)
 '(global-whitespace-mode t)
 '(google-translate-default-source-language "en")
 '(google-translate-default-target-language "ja")
 '(google-translate-pop-up-buffer-set-focus t)
 '(grep-find-command "/usr/bin/find")
 '(indent-tabs-mode nil)
 '(initial-major-mode (quote text-mode))
 '(js2-basic-offset 2)
 '(js2-highlight-external-variables nil)
 '(js2-include-browser-externs nil)
 '(js2-include-jslint-globals nil)
 '(js2-mode-show-parse-errors nil)
 '(js2-mode-show-strict-warnings nil)
 '(json-reformat:indent-width 2)
 '(markdown-asymmetric-header t)
 '(markdown-hide-urls t)
 '(markdown-list-indent-width 2)
 '(markdown-open-command "cygstart")
 '(open-junk-file-directory "~/.emacs.d/var/junk/%Y-%m-%d-%H%M%S." t)
 '(org-web-tools-pandoc-sleep-time 2.0)
 '(package-selected-packages
   (quote
    (all-the-icons itail textile-mode highlight-indent-guides pocket-reader kotlin-mode restclient yaml-mode yasnippet wgrep-ag web-beautify visual-regexp undo-tree sass-mode ripgrep pug-mode pt open-junk-file markdown-toc json-mode js2-mode js-doc jdee gradle-mode google-translate ensime emojify emoji-cheat-sheet-plus dashboard ample-zen-theme ag)))
 '(pocket-reader-color-site nil)
 '(pocket-reader-color-title nil)
 '(pocket-reader-show-count 100)
 '(prog-mode-hook (quote (highlight-indent-guides-mode)))
 '(projectile-cache-file "~/.emacs.d/var/projectile/projectile.cache")
 '(projectile-known-projects-file "~/.emacs.d/var/projectile/projectile-bookmarks.eld")
 '(python-indent-offset 2)
 '(read-buffer-completion-ignore-case t)
 '(recentf-max-saved-items 3000)
 '(recentf-save-file "~/.emacs.d/var/recentf")
 '(ripgrep-arguments (quote ("--sort path")))
 '(sbt:program-name "cygsbt")
 '(scala-indent:use-javadoc-style t)
 '(sh-basic-offset 2)
 '(sh-indentation 2)
 '(show-paren-mode t)
 '(tab-width 2)
 '(truncate-lines t)
 '(truncate-partial-width-windows nil)
 '(url-cache-directory "~/.emacs.d/var/url/cache")
 '(url-configuration-directory "~/.emacs.d/var/url/")
 '(visible-bell t)
 '(web-mode-css-indent-offset 2)
 '(web-mode-enable-current-column-highlight t)
 '(web-mode-enable-current-element-highlight t)
 '(web-mode-markup-indent-offset 2)
 '(web-mode-sql-indent-offset 2)
 '(whitespace-action (quote (auto-cleanup)))
 '(whitespace-style
   (quote
    (trailing space-before-tab indentation empty space-after-tab)))
 '(yas-global-mode t)
 '(yas-prompt-functions (quote (yas-maybe-ido-prompt yas-no-prompt)))
 '(yas-snippet-dirs
   (quote
    ("~/.emacs.d/etc/snippets" "~/.emacs.d/site-lisp/yasnippet/snippets" yasnippet-snippets-dir))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
